appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: p//HypbphhB74kDFwcqaYu5DM5qfeL4cDR4F38VWmBABrerkL31LcNnMH4oE5aJfZxELrsUuf+o71tUSF/YECqpW0hFB1ARGdgTgHqsmETm5ijwfa6wsp4aO4Vzy/4idzmiLx8bxF4WMHVvOvMMAmYEC5iftwOto+2PdnUhkGj99+mA/kZ2YvanzWb/qV2NkxDC3xJcPOf6bl4bR2rAQThV7kDKh3u0KLylccMUstp69Zp5w25pU6JicizXy7ktq7z1OrIyE2qUWV0jrNVJpJBIL14E0p8MuNAd8OI5VNG+67lLBLY0aMI8ERgTAozlemaFRaY+LULyYG5ulGrj5FIPSC5cCJGxyrsLlR8eWJXgZiVQ50r9FEEpSW34Gr+ScDS86Un0dzDKCl0j0DbjRVL09YcS5vxKhLIQ4CEE0RnTpmG8SVnsXJQ/Bd5oWC0O8LRqse0HBuXuuDwKhJb5Id74Cnj/VvpM4l+McYPOOy49gpCsF5IuQsKlHDGmakjQgJBEuVCnrUKZstuNG4mRDhPaLz1CtGxlCgOeVpepXyJAp4PSmi0DOQcVl/53F2WiRpuG+LrGQuigk/okV2PEfZRq/kw0EpdzTcbfuWv+yZ7YS827ifDFblqed/8q+Dwr4QBLts7un4CpjX0ZAah5oZPpC9NCXH5H3U+mFC1bRTsY=}
conda_forge_output_validation: true
